# Generated by Django 5.2.6 on 2025-09-21 04:36

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coverage',
            fields=[
                ('created_by', models.CharField(blank=True, editable=False, max_length=250, null=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='INR', max_length=10)),
                ('eligibility_criteria', models.TextField(blank=True, null=True)),
                ('max_coverage_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('status', models.CharField(choices=[('active', 'Active'), ('inactive', 'Inactive')], default='active', max_length=8)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CustomerCoverage',
            fields=[
                ('created_by', models.CharField(blank=True, editable=False, max_length=250, null=True)),
                ('modified_by', models.CharField(blank=True, editable=False, max_length=250, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('customer_id', models.UUIDField()),
                ('policy_id', models.UUIDField(blank=True, null=True)),
                ('effective_date', models.DateField()),
                ('expiry_date', models.DateField()),
                ('premium', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('active', 'Active'), ('expired', 'Expired'), ('cancelled', 'Cancelled')], default='active', max_length=9)),
                ('coverage', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_coverages', to='coverages.coverage')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
